version: '3.8'
services:
  dev-db:
    image: arm64v8/postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - 5434:5432
    networks:
      - bookmark-network
  test-db:
    image: arm64v8/postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - 5435:5432
    networks:
      - bookmark-network
networks:
  bookmark-network:
